# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lingon < Formula
  desc "Lingon binaries:
- explode is a command line tool to organize kubernetes manifests according to their kind. (YAML to YAML)
- kygo is a command line tool to convert kubernetes YAML manifests to Go structs. (YAML to Go)
- terragen generates Go code for Terraform providers.
"
  homepage "https://github.com/volvo-cars/lingon"
  version "2023-04-15-42a3a13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/volvo-cars/lingon/releases/download/2023-04-15-42a3a13/lingon_2023-04-15-42a3a13_darwin_amd64.tar.gz"
      sha256 "73786f400b46e5d4d4e1bc8010040f7178170b37b4183268d72978af8e4a0274"

      def install
        bin.install "explode"
        bin.install "kygo"
        bin.install "terragen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/volvo-cars/lingon/releases/download/2023-04-15-42a3a13/lingon_2023-04-15-42a3a13_darwin_arm64.tar.gz"
      sha256 "59eb775af468810338492ad8a22dd1a23ef104d144b5ef9bd41d9a0f1e4d879a"

      def install
        bin.install "explode"
        bin.install "kygo"
        bin.install "terragen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/volvo-cars/lingon/releases/download/2023-04-15-42a3a13/lingon_2023-04-15-42a3a13_linux_arm64.tar.gz"
      sha256 "7f15765f667cbbecd133b83daa43283ce47673cf356301ecd4a118adb5de4b30"

      def install
        bin.install "explode"
        bin.install "kygo"
        bin.install "terragen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/volvo-cars/lingon/releases/download/2023-04-15-42a3a13/lingon_2023-04-15-42a3a13_linux_amd64.tar.gz"
      sha256 "b1ca7b6ac4bac196dfc576d7bb1222c7551f499512a62f80793da66fec38d0b6"

      def install
        bin.install "explode"
        bin.install "kygo"
        bin.install "terragen"
      end
    end
  end

  test do
    system "#{bin}/explode -v"
    system "#{bin}/kygo -v"
    system "#{bin}/terragen -v"
  end
end
