# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lingon < Formula
  desc "Lingon binaries:
- explode is a command line tool to organize kubernetes manifests according to their kind. (YAML to YAML)
- kygo is a command line tool to convert kubernetes YAML manifests to Go structs. (YAML to Go)
- terragen generates Go code for Terraform providers.
"
  homepage "https://github.com/volvo-cars/lingon"
  version "2023-04-08-cdc2f49"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/volvo-cars/lingon/releases/download/2023-04-08-cdc2f49/lingon_2023-04-08-cdc2f49_darwin_amd64.tar.gz"
      sha256 "654fe13dbfdc242df3f3bfcfcd527aaa202fc4cefaae5b50919cf2caabf3431f"

      def install
        bin.install "explode"
        bin.install "kygo"
        bin.install "terragen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/volvo-cars/lingon/releases/download/2023-04-08-cdc2f49/lingon_2023-04-08-cdc2f49_darwin_arm64.tar.gz"
      sha256 "5b30deab4e06fb390b15c22d4d817250e2fbd4f8a5897372a694f722c387bb17"

      def install
        bin.install "explode"
        bin.install "kygo"
        bin.install "terragen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/volvo-cars/lingon/releases/download/2023-04-08-cdc2f49/lingon_2023-04-08-cdc2f49_linux_amd64.tar.gz"
      sha256 "11d8ed1cae8d54540c8c14db3d25824257154d967a8928f15c261ccfca7e775e"

      def install
        bin.install "explode"
        bin.install "kygo"
        bin.install "terragen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/volvo-cars/lingon/releases/download/2023-04-08-cdc2f49/lingon_2023-04-08-cdc2f49_linux_arm64.tar.gz"
      sha256 "4b8b493c5386bc0b4b10965ef2363ce6e2f37348f6a342b36c8b149b66c3eab9"

      def install
        bin.install "explode"
        bin.install "kygo"
        bin.install "terragen"
      end
    end
  end

  test do
    system "#{bin}/explode -v"
    system "#{bin}/kygo -v"
    system "#{bin}/terragen -v"
  end
end
