# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lingon < Formula
  desc "Lingon binaries:
- explode is a command line tool to organize kubernetes manifests according to their kind. (YAML to YAML)
- kygo is a command line tool to convert kubernetes YAML manifests to Go structs. (YAML to Go)
- terragen generates Go code for Terraform providers.
"
  homepage "https://github.com/volvo-cars/lingon"
  version "2023-04-26-57f742a"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/volvo-cars/lingon/releases/download/2023-04-26-57f742a/lingon_2023-04-26-57f742a_darwin_arm64.tar.gz"
      sha256 "2537b561561210889c9b09944038e5d5709e208976f0b263c8ad90f3e9206888"

      def install
        bin.install "explode"
        bin.install "kygo"
        bin.install "terragen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/volvo-cars/lingon/releases/download/2023-04-26-57f742a/lingon_2023-04-26-57f742a_darwin_amd64.tar.gz"
      sha256 "82919bdf512395207beb0e497ae4b11da980b736effa9d849eadef3123147757"

      def install
        bin.install "explode"
        bin.install "kygo"
        bin.install "terragen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/volvo-cars/lingon/releases/download/2023-04-26-57f742a/lingon_2023-04-26-57f742a_linux_arm64.tar.gz"
      sha256 "b15bd84315bfbc137ddd57d9697d1c876d2b93e7d73de9a55518e9b32a521956"

      def install
        bin.install "explode"
        bin.install "kygo"
        bin.install "terragen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/volvo-cars/lingon/releases/download/2023-04-26-57f742a/lingon_2023-04-26-57f742a_linux_amd64.tar.gz"
      sha256 "8eb054d474435266d2f96b7fae39e0246e485c20b7f699650adfb7f4b5ec3d7a"

      def install
        bin.install "explode"
        bin.install "kygo"
        bin.install "terragen"
      end
    end
  end

  test do
    system "#{bin}/explode -v"
    system "#{bin}/kygo -v"
    system "#{bin}/terragen -v"
  end
end
